insert into pais (sigla,nome) values ('AF', 'Afghanistan');
insert into pais (sigla,nome) values ('AL', 'Albania');
insert into pais (sigla,nome) values ('DZ', 'Algeria');
insert into pais (sigla,nome) values ('DS', 'American Samoa');
insert into pais (sigla,nome) values ('AD', 'Andorra');
insert into pais (sigla,nome) values ('AO', 'Angola');
insert into pais (sigla,nome) values ('AI', 'Anguilla');
insert into pais (sigla,nome) values ('AQ', 'Antarctica');
insert into pais (sigla,nome) values ('AG', 'Antigua and Barbuda');
insert into pais (sigla,nome) values ('AR', 'Argentina');
insert into pais (sigla,nome) values ('AM', 'Armenia');
insert into pais (sigla,nome) values ('AW', 'Aruba');
insert into pais (sigla,nome) values ('AU', 'Australia');
insert into pais (sigla,nome) values ('AT', 'Austria');
insert into pais (sigla,nome) values ('AZ', 'Azerbaijan');
insert into pais (sigla,nome) values ('BS', 'Bahamas');
insert into pais (sigla,nome) values ('BH', 'Bahrain');
insert into pais (sigla,nome) values ('BD', 'Bangladesh');
insert into pais (sigla,nome) values ('BB', 'Barbados');
insert into pais (sigla,nome) values ('BY', 'Belarus');
insert into pais (sigla,nome) values ('BE', 'Belgium');
insert into pais (sigla,nome) values ('BZ', 'Belize');
insert into pais (sigla,nome) values ('BJ', 'Benin');
insert into pais (sigla,nome) values ('BM', 'Bermuda');
insert into pais (sigla,nome) values ('BT', 'Bhutan');
insert into pais (sigla,nome) values ('BO', 'Bolivia');
insert into pais (sigla,nome) values ('BA', 'Bosnia and Herzegovina');
insert into pais (sigla,nome) values ('BW', 'Botswana');
insert into pais (sigla,nome) values ('BV', 'Bouvet Island');
insert into pais (sigla,nome) values ('BR', 'Brazil');
insert into pais (sigla,nome) values ('IO', 'British Indian Ocean Territory');
insert into pais (sigla,nome) values ('BN', 'Brunei Darussalam');
insert into pais (sigla,nome) values ('BG', 'Bulgaria');
insert into pais (sigla,nome) values ('BF', 'Burkina Faso');
insert into pais (sigla,nome) values ('BI', 'Burundi');
insert into pais (sigla,nome) values ('KH', 'Cambodia');
insert into pais (sigla,nome) values ('CM', 'Cameroon');
insert into pais (sigla,nome) values ('CA', 'Canada');
insert into pais (sigla,nome) values ('CV', 'Cape Verde');
insert into pais (sigla,nome) values ('KY', 'Cayman Islands');
insert into pais (sigla,nome) values ('CF', 'Central African Republic');
insert into pais (sigla,nome) values ('TD', 'Chad');
insert into pais (sigla,nome) values ('CL', 'Chile');
insert into pais (sigla,nome) values ('CN', 'China');
insert into pais (sigla,nome) values ('CX', 'Christmas Island');
insert into pais (sigla,nome) values ('CC', 'Cocos (Keeling) Islands');
insert into pais (sigla,nome) values ('CO', 'Colombia');
insert into pais (sigla,nome) values ('KM', 'Comoros');
insert into pais (sigla,nome) values ('CG', 'Congo');
insert into pais (sigla,nome) values ('CK', 'Cook Islands');
insert into pais (sigla,nome) values ('CR', 'Costa Rica');
insert into pais (sigla,nome) values ('HR', 'Croatia (Hrvatska)');
insert into pais (sigla,nome) values ('CU', 'Cuba');
insert into pais (sigla,nome) values ('CY', 'Cyprus');
insert into pais (sigla,nome) values ('CZ', 'Czech Republic');
insert into pais (sigla,nome) values ('DK', 'Denmark');
insert into pais (sigla,nome) values ('DJ', 'Djibouti');
insert into pais (sigla,nome) values ('DM', 'Dominica');
insert into pais (sigla,nome) values ('DO', 'Dominican Republic');
insert into pais (sigla,nome) values ('TP', 'East Timor');
insert into pais (sigla,nome) values ('EC', 'Ecuador');
insert into pais (sigla,nome) values ('EG', 'Egypt');
insert into pais (sigla,nome) values ('SV', 'El Salvador');
insert into pais (sigla,nome) values ('GQ', 'Equatorial Guinea');
insert into pais (sigla,nome) values ('ER', 'Eritrea');
insert into pais (sigla,nome) values ('EE', 'Estonia');
insert into pais (sigla,nome) values ('ET', 'Ethiopia');
insert into pais (sigla,nome) values ('FK', 'Falkland Islands (Malvinas)');
insert into pais (sigla,nome) values ('FO', 'Faroe Islands');
insert into pais (sigla,nome) values ('FJ', 'Fiji');
insert into pais (sigla,nome) values ('FI', 'Finland');
insert into pais (sigla,nome) values ('FR', 'France');
insert into pais (sigla,nome) values ('FX', 'France, Metropolitan');
insert into pais (sigla,nome) values ('GF', 'French Guiana');
insert into pais (sigla,nome) values ('PF', 'French Polynesia');
insert into pais (sigla,nome) values ('TF', 'French Southern Territories');
insert into pais (sigla,nome) values ('GA', 'Gabon');
insert into pais (sigla,nome) values ('GM', 'Gambia');
insert into pais (sigla,nome) values ('GE', 'Georgia');
insert into pais (sigla,nome) values ('DE', 'Germany');
insert into pais (sigla,nome) values ('GH', 'Ghana');
insert into pais (sigla,nome) values ('GI', 'Gibraltar');
insert into pais (sigla,nome) values ('GK', 'Guernsey');
insert into pais (sigla,nome) values ('GR', 'Greece');
insert into pais (sigla,nome) values ('GL', 'Greenland');
insert into pais (sigla,nome) values ('GD', 'Grenada');
insert into pais (sigla,nome) values ('GP', 'Guadeloupe');
insert into pais (sigla,nome) values ('GU', 'Guam');
insert into pais (sigla,nome) values ('GT', 'Guatemala');
insert into pais (sigla,nome) values ('GN', 'Guinea');
insert into pais (sigla,nome) values ('GW', 'Guinea-Bissau');
insert into pais (sigla,nome) values ('GY', 'Guyana');
insert into pais (sigla,nome) values ('HT', 'Haiti');
insert into pais (sigla,nome) values ('HM', 'Heard and Mc Donald Islands');
insert into pais (sigla,nome) values ('HN', 'Honduras');
insert into pais (sigla,nome) values ('HK', 'Hong Kong');
insert into pais (sigla,nome) values ('HU', 'Hungary');
insert into pais (sigla,nome) values ('IS', 'Iceland');
insert into pais (sigla,nome) values ('IN', 'India');
insert into pais (sigla,nome) values ('IM', 'Isle of Man');
insert into pais (sigla,nome) values ('ID', 'Indonesia');
insert into pais (sigla,nome) values ('IR', 'Iran (Islamic Republic of)');
insert into pais (sigla,nome) values ('IQ', 'Iraq');
insert into pais (sigla,nome) values ('IE', 'Ireland');
insert into pais (sigla,nome) values ('IL', 'Israel');
insert into pais (sigla,nome) values ('IT', 'Italy');
insert into pais (sigla,nome) values ('CI', 'Ivory Coast');
insert into pais (sigla,nome) values ('JE', 'Jersey');
insert into pais (sigla,nome) values ('JM', 'Jamaica');
insert into pais (sigla,nome) values ('JP', 'Japan');
insert into pais (sigla,nome) values ('JO', 'Jordan');
insert into pais (sigla,nome) values ('KZ', 'Kazakhstan');
insert into pais (sigla,nome) values ('KE', 'Kenya');
insert into pais (sigla,nome) values ('KI', 'Kiribati');
insert into pais (sigla,nome) values ('KP', 'Korea, Democratic People''s Republic of');
insert into pais (sigla,nome) values ('KR', 'Korea, Republic of');
insert into pais (sigla,nome) values ('XK', 'Kosovo');
insert into pais (sigla,nome) values ('KW', 'Kuwait');
insert into pais (sigla,nome) values ('KG', 'Kyrgyzstan');
insert into pais (sigla,nome) values ('LA', 'Lao People''s Democratic Republic');
insert into pais (sigla,nome) values ('LV', 'Latvia');
insert into pais (sigla,nome) values ('LB', 'Lebanon');
insert into pais (sigla,nome) values ('LS', 'Lesotho');
insert into pais (sigla,nome) values ('LR', 'Liberia');
insert into pais (sigla,nome) values ('LY', 'Libyan Arab Jamahiriya');
insert into pais (sigla,nome) values ('LI', 'Liechtenstein');
insert into pais (sigla,nome) values ('LT', 'Lithuania');
insert into pais (sigla,nome) values ('LU', 'Luxembourg');
insert into pais (sigla,nome) values ('MO', 'Macau');
insert into pais (sigla,nome) values ('MK', 'Macedonia');
insert into pais (sigla,nome) values ('MG', 'Madagascar');
insert into pais (sigla,nome) values ('MW', 'Malawi');
insert into pais (sigla,nome) values ('MY', 'Malaysia');
insert into pais (sigla,nome) values ('MV', 'Maldives');
insert into pais (sigla,nome) values ('ML', 'Mali');
insert into pais (sigla,nome) values ('MT', 'Malta');
insert into pais (sigla,nome) values ('MH', 'Marshall Islands');
insert into pais (sigla,nome) values ('MQ', 'Martinique');
insert into pais (sigla,nome) values ('MR', 'Mauritania');
insert into pais (sigla,nome) values ('MU', 'Mauritius');
insert into pais (sigla,nome) values ('TY', 'Mayotte');
insert into pais (sigla,nome) values ('MX', 'Mexico');
insert into pais (sigla,nome) values ('FM', 'Micronesia, Federated States of');
insert into pais (sigla,nome) values ('MD', 'Moldova, Republic of');
insert into pais (sigla,nome) values ('MC', 'Monaco');
insert into pais (sigla,nome) values ('MN', 'Mongolia');
insert into pais (sigla,nome) values ('ME', 'Montenegro');
insert into pais (sigla,nome) values ('MS', 'Montserrat');
insert into pais (sigla,nome) values ('MA', 'Morocco');
insert into pais (sigla,nome) values ('MZ', 'Mozambique');
insert into pais (sigla,nome) values ('MM', 'Myanmar');
insert into pais (sigla,nome) values ('NA', 'Namibia');
insert into pais (sigla,nome) values ('NR', 'Nauru');
insert into pais (sigla,nome) values ('NP', 'Nepal');
insert into pais (sigla,nome) values ('NL', 'Netherlands');
insert into pais (sigla,nome) values ('AN', 'Netherlands Antilles');
insert into pais (sigla,nome) values ('NC', 'New Caledonia');
insert into pais (sigla,nome) values ('NZ', 'New Zealand');
insert into pais (sigla,nome) values ('NI', 'Nicaragua');
insert into pais (sigla,nome) values ('NE', 'Niger');
insert into pais (sigla,nome) values ('NG', 'Nigeria');
insert into pais (sigla,nome) values ('NU', 'Niue');
insert into pais (sigla,nome) values ('NF', 'Norfolk Island');
insert into pais (sigla,nome) values ('MP', 'Northern Mariana Islands');
insert into pais (sigla,nome) values ('NO', 'Norway');
insert into pais (sigla,nome) values ('OM', 'Oman');
insert into pais (sigla,nome) values ('PK', 'Pakistan');
insert into pais (sigla,nome) values ('PW', 'Palau');
insert into pais (sigla,nome) values ('PS', 'Palestine');
insert into pais (sigla,nome) values ('PA', 'Panama');
insert into pais (sigla,nome) values ('PG', 'Papua New Guinea');
insert into pais (sigla,nome) values ('PY', 'Paraguay');
insert into pais (sigla,nome) values ('PE', 'Peru');
insert into pais (sigla,nome) values ('PH', 'Philippines');
insert into pais (sigla,nome) values ('PN', 'Pitcairn');
insert into pais (sigla,nome) values ('PL', 'Poland');
insert into pais (sigla,nome) values ('PT', 'Portugal');
insert into pais (sigla,nome) values ('PR', 'Puerto Rico');
insert into pais (sigla,nome) values ('QA', 'Qatar');
insert into pais (sigla,nome) values ('RE', 'Reunion');
insert into pais (sigla,nome) values ('RO', 'Romania');
insert into pais (sigla,nome) values ('RU', 'Russian Federation');
insert into pais (sigla,nome) values ('RW', 'Rwanda');
insert into pais (sigla,nome) values ('KN', 'Saint Kitts and Nevis');
insert into pais (sigla,nome) values ('LC', 'Saint Lucia');
insert into pais (sigla,nome) values ('VC', 'Saint Vincent and the Grenadines');
insert into pais (sigla,nome) values ('WS', 'Samoa');
insert into pais (sigla,nome) values ('SM', 'San Marino');
insert into pais (sigla,nome) values ('ST', 'Sao Tome and Principe');
insert into pais (sigla,nome) values ('SA', 'Saudi Arabia');
insert into pais (sigla,nome) values ('SN', 'Senegal');
insert into pais (sigla,nome) values ('RS', 'Serbia');
insert into pais (sigla,nome) values ('SC', 'Seychelles');
insert into pais (sigla,nome) values ('SL', 'Sierra Leone');
insert into pais (sigla,nome) values ('SG', 'Singapore');
insert into pais (sigla,nome) values ('SK', 'Slovakia');
insert into pais (sigla,nome) values ('SI', 'Slovenia');
insert into pais (sigla,nome) values ('SB', 'Solomon Islands');
insert into pais (sigla,nome) values ('SO', 'Somalia');
insert into pais (sigla,nome) values ('ZA', 'South Africa');
insert into pais (sigla,nome) values ('GS', 'South Georgia South Sandwich Islands');
insert into pais (sigla,nome) values ('ES', 'Spain');
insert into pais (sigla,nome) values ('LK', 'Sri Lanka');
insert into pais (sigla,nome) values ('SH', 'St. Helena');
insert into pais (sigla,nome) values ('PM', 'St. Pierre and Miquelon');
insert into pais (sigla,nome) values ('SD', 'Sudan');
insert into pais (sigla,nome) values ('SR', 'Suriname');
insert into pais (sigla,nome) values ('SJ', 'Svalbard and Jan Mayen Islands');
insert into pais (sigla,nome) values ('SZ', 'Swaziland');
insert into pais (sigla,nome) values ('SE', 'Sweden');
insert into pais (sigla,nome) values ('CH', 'Switzerland');
insert into pais (sigla,nome) values ('SY', 'Syrian Arab Republic');
insert into pais (sigla,nome) values ('TW', 'Taiwan');
insert into pais (sigla,nome) values ('TJ', 'Tajikistan');
insert into pais (sigla,nome) values ('TZ', 'Tanzania, United Republic of');
insert into pais (sigla,nome) values ('TH', 'Thailand');
insert into pais (sigla,nome) values ('TG', 'Togo');
insert into pais (sigla,nome) values ('TK', 'Tokelau');
insert into pais (sigla,nome) values ('TO', 'Tonga');
insert into pais (sigla,nome) values ('TT', 'Trinidad and Tobago');
insert into pais (sigla,nome) values ('TN', 'Tunisia');
insert into pais (sigla,nome) values ('TR', 'Turkey');
insert into pais (sigla,nome) values ('TM', 'Turkmenistan');
insert into pais (sigla,nome) values ('TC', 'Turks and Caicos Islands');
insert into pais (sigla,nome) values ('TV', 'Tuvalu');
insert into pais (sigla,nome) values ('UG', 'Uganda');
insert into pais (sigla,nome) values ('UA', 'Ukraine');
insert into pais (sigla,nome) values ('AE', 'United Arab Emirates');
insert into pais (sigla,nome) values ('GB', 'United Kingdom');
insert into pais (sigla,nome) values ('US', 'United States');
insert into pais (sigla,nome) values ('UM', 'United States minor outlying islands');
insert into pais (sigla,nome) values ('UY', 'Uruguay');
insert into pais (sigla,nome) values ('UZ', 'Uzbekistan');
insert into pais (sigla,nome) values ('VU', 'Vanuatu');
insert into pais (sigla,nome) values ('VA', 'Vatican City State');
insert into pais (sigla,nome) values ('VE', 'Venezuela');
insert into pais (sigla,nome) values ('VN', 'Vietnam');
insert into pais (sigla,nome) values ('VG', 'Virgin Islands (British)');
insert into pais (sigla,nome) values ('VI', 'Virgin Islands (U.S.)');
insert into pais (sigla,nome) values ('WF', 'Wallis and Futuna Islands');
insert into pais (sigla,nome) values ('EH', 'Western Sahara');
insert into pais (sigla,nome) values ('YE', 'Yemen');
insert into pais (sigla,nome) values ('YU', 'Yugoslavia');
insert into pais (sigla,nome) values ('ZR', 'Zaire');
insert into pais (sigla,nome) values ('ZM', 'Zambia');
insert into pais (sigla,nome) values ('ZW', 'Zimbabwe');
insert into estado (nome,sigla,pais_id) values ('Asunción', '', 172);
insert into estado (nome,sigla,pais_id) values ('Concepción', '', 172);
insert into estado (nome,sigla,pais_id) values ('San Pedro', '', 172);
insert into estado (nome,sigla,pais_id) values ('Cordillera', '', 172);
insert into estado (nome,sigla,pais_id) values ('Guairá', '', 172);
insert into estado (nome,sigla,pais_id) values ('Caaguazú', '', 172);
insert into estado (nome,sigla,pais_id) values ('Caazapá', '', 172);
insert into estado (nome,sigla,pais_id) values ('Itapúa', '', 172);
insert into estado (nome,sigla,pais_id) values ('Misiones', '', 172);
insert into estado (nome,sigla,pais_id) values ('Paraguarí', '', 172);
insert into estado (nome,sigla,pais_id) values ('Alto Paraná', '', 172);
insert into estado (nome,sigla,pais_id) values ('Central', '', 172);
insert into estado (nome,sigla,pais_id) values ('Ñeembucú', '', 172);
insert into estado (nome,sigla,pais_id) values ('Amambay', '', 172);
insert into estado (nome,sigla,pais_id) values ('Canindeyú', '', 172);
insert into estado (nome,sigla,pais_id) values ('Presidente Hayes', '', 172);
insert into estado (nome,sigla,pais_id) values ('Boquerón', '', 172);
insert into estado (nome,sigla,pais_id) values ('Alto Paraguay', '', 172);
insert into estado (nome,sigla,pais_id) values ('Alaska', 'AK', 230);
insert into estado (nome,sigla,pais_id) values ('Alabama', 'AL', 230);
insert into estado (nome,sigla,pais_id) values ('Arkansas', 'AR', 230);
insert into estado (nome,sigla,pais_id) values ('Arizona', 'AZ', 230);
insert into estado (nome,sigla,pais_id) values ('California', 'CA', 230);
insert into estado (nome,sigla,pais_id) values ('Colorado', 'CO', 230);
insert into estado (nome,sigla,pais_id) values ('Connecticut', 'CT', 230);
insert into estado (nome,sigla,pais_id) values ('District of Columbia', 'DC', 230);
insert into estado (nome,sigla,pais_id) values ('Delaware', 'DE', 230);
insert into estado (nome,sigla,pais_id) values ('Florida', 'FL', 230);
insert into estado (nome,sigla,pais_id) values ('Georgia', 'GA', 230);
insert into estado (nome,sigla,pais_id) values ('Hawaii', 'HI', 230);
insert into estado (nome,sigla,pais_id) values ('Iowa', 'IA', 230);
insert into estado (nome,sigla,pais_id) values ('Idaho', 'ID', 230);
insert into estado (nome,sigla,pais_id) values ('Illinois', 'IL', 230);
insert into estado (nome,sigla,pais_id) values ('Indiana', 'IN', 230);
insert into estado (nome,sigla,pais_id) values ('Kansas', 'KS', 230);
insert into estado (nome,sigla,pais_id) values ('Kentucky', 'KY', 230);
insert into estado (nome,sigla,pais_id) values ('Louisiana', 'LA', 230);
insert into estado (nome,sigla,pais_id) values ('Massachusetts', 'MA', 230);
insert into estado (nome,sigla,pais_id) values ('Maryland', 'MD', 230);
insert into estado (nome,sigla,pais_id) values ('Maine', 'ME', 230);
insert into estado (nome,sigla,pais_id) values ('Michigan', 'MI', 230);
insert into estado (nome,sigla,pais_id) values ('Minnesota', 'MN', 230);
insert into estado (nome,sigla,pais_id) values ('Missouri', 'MO', 230);
insert into estado (nome,sigla,pais_id) values ('Mississippi', 'MS', 230);
insert into estado (nome,sigla,pais_id) values ('Montana', 'MT', 230);
insert into estado (nome,sigla,pais_id) values ('North Carolina', 'NC', 230);
insert into estado (nome,sigla,pais_id) values ('North Dakota', 'ND', 230);
insert into estado (nome,sigla,pais_id) values ('Nebraska', 'NE', 230);
insert into estado (nome,sigla,pais_id) values ('New Hampshire', 'NH', 230);
insert into estado (nome,sigla,pais_id) values ('New Jersey', 'NJ', 230);
insert into estado (nome,sigla,pais_id) values ('New Mexico', 'NM', 230);
insert into estado (nome,sigla,pais_id) values ('Nevada', 'NV', 230);
insert into estado (nome,sigla,pais_id) values ('New York', 'NY', 230);
insert into estado (nome,sigla,pais_id) values ('Ohio', 'OH', 230);
insert into estado (nome,sigla,pais_id) values ('Oklahoma', 'OK', 230);
insert into estado (nome,sigla,pais_id) values ('Oregon', 'OR', 230);
insert into estado (nome,sigla,pais_id) values ('Pennsylvania', 'PA', 230);
insert into estado (nome,sigla,pais_id) values ('Rhode Island', 'RI', 230);
insert into estado (nome,sigla,pais_id) values ('South Carolina', 'SC', 230);
insert into estado (nome,sigla,pais_id) values ('South Dakota', 'SD', 230);
insert into estado (nome,sigla,pais_id) values ('Tennessee', 'TN', 230);
insert into estado (nome,sigla,pais_id) values ('Texas', 'TX', 230);
insert into estado (nome,sigla,pais_id) values ('Utah', 'UT', 230);
insert into estado (nome,sigla,pais_id) values ('Virginia', 'VA', 230);
insert into estado (nome,sigla,pais_id) values ('Vermont', 'VT', 230);
insert into estado (nome,sigla,pais_id) values ('Washington', 'WA', 230);
insert into estado (nome,sigla,pais_id) values ('Wisconsin', 'WI', 230);
insert into estado (nome,sigla,pais_id) values ('West Virginia', 'WV', 230);
insert into estado (nome,sigla,pais_id) values ('Wyoming', 'WY', 230);
insert into estado (nome,sigla,pais_id) values ('Acre', 'AC', 30);
insert into estado (nome,sigla,pais_id) values ('Alagoas', 'AL', 30);
insert into estado (nome,sigla,pais_id) values ('Amazonas', 'AM', 30);
insert into estado (nome,sigla,pais_id) values ('Amapá', 'AP', 30);
insert into estado (nome,sigla,pais_id) values ('Bahia', 'BA', 30);
insert into estado (nome,sigla,pais_id) values ('Ceará', 'CE', 30);
insert into estado (nome,sigla,pais_id) values ('Distrito Federal', 'DF', 30);
insert into estado (nome,sigla,pais_id) values ('Espírito Santo', 'ES', 30);
insert into estado (nome,sigla,pais_id) values ('Goiás', 'GO', 30);
insert into estado (nome,sigla,pais_id) values ('Maranhão', 'MA', 30);
insert into estado (nome,sigla,pais_id) values ('Minas Gerais', 'MG', 30);
insert into estado (nome,sigla,pais_id) values ('Mato Grosso do Sul', 'MS', 30);
insert into estado (nome,sigla,pais_id) values ('Mato Grosso', 'MT', 30);
insert into estado (nome,sigla,pais_id) values ('Pará', 'PA', 30);
insert into estado (nome,sigla,pais_id) values ('Paraíba', 'PB', 30);
insert into estado (nome,sigla,pais_id) values ('Pernambuco', 'PE', 30);
insert into estado (nome,sigla,pais_id) values ('Piauí', 'PI', 30);
insert into estado (nome,sigla,pais_id) values ('Paraná', 'PR', 30);
insert into estado (nome,sigla,pais_id) values ('Rio de Janeiro', 'RJ', 30);
insert into estado (nome,sigla,pais_id) values ('Rio Grande do Norte', 'RN', 30);
insert into estado (nome,sigla,pais_id) values ('Rondônia', 'RO', 30);
insert into estado (nome,sigla,pais_id) values ('Roraima', 'RR', 30);
insert into estado (nome,sigla,pais_id) values ('Rio Grande do Sul', 'RS', 30);
insert into estado (nome,sigla,pais_id) values ('Santa Catarina', 'SC', 30);
insert into estado (nome,sigla,pais_id) values ('Sergipe', 'SE', 30);
insert into estado (nome,sigla,pais_id) values ('São Paulo', 'SP', 30);
insert into estado (nome,sigla,pais_id) values ('Tocantins', 'TO', 30);
insert into estado (nome,sigla,pais_id) values ('BUENOS AIRES', '', 10);
insert into estado (nome,sigla,pais_id) values ('CATAMARCA', '', 10);
insert into estado (nome,sigla,pais_id) values ('CHACO', '', 10);
insert into estado (nome,sigla,pais_id) values ('CHUBUT', '', 10);
insert into estado (nome,sigla,pais_id) values ('CORDOBA', '', 10);
insert into estado (nome,sigla,pais_id) values ('CORRIENTES', '', 10);
insert into estado (nome,sigla,pais_id) values ('ENTRE RIOS', '', 10);
insert into estado (nome,sigla,pais_id) values ('FORMOSA', '', 10);
insert into estado (nome,sigla,pais_id) values ('JUJUY', '', 10);
insert into estado (nome,sigla,pais_id) values ('LA PAMPA', '', 10);
insert into estado (nome,sigla,pais_id) values ('LA RIOJA', '', 10);
insert into estado (nome,sigla,pais_id) values ('MENDOZA', '', 10);
insert into estado (nome,sigla,pais_id) values ('MISIONES', '', 10);
insert into estado (nome,sigla,pais_id) values ('NEUQUEN', '', 10);
insert into estado (nome,sigla,pais_id) values ('RIO NEGRO', '', 10);
insert into estado (nome,sigla,pais_id) values ('SALTA', '', 10);
insert into estado (nome,sigla,pais_id) values ('SAN JUAN', '', 10);
insert into estado (nome,sigla,pais_id) values ('SAN LUIS', '', 10);
insert into estado (nome,sigla,pais_id) values ('SANTA CRUZ', '', 10);
insert into estado (nome,sigla,pais_id) values ('SANTA FE', '', 10);
insert into estado (nome,sigla,pais_id) values ('SANTIAGO DEL ESTERO', '', 10);
insert into estado (nome,sigla,pais_id) values ('TIERRA DEL FUEGO', '', 10);
insert into estado (nome,sigla,pais_id) values ('TUCUMAN', '', 10);
insert into cidade (nome,estado_id) values ('Foz do Iguaçu', 87);
insert into cidade (nome,estado_id) values ('Curitiba', 87);
insert into cidade (nome,estado_id) values ('Campo Mourão', 87);
insert into cidade (nome,estado_id) values ('Pato Branco', 87);
insert into cidade (nome,estado_id) values ('Cascavel', 87);
insert into cidade (nome,estado_id) values ('São Miguel', 87);
insert into cidade (nome,estado_id) values ('Campo Largo', 87);
insert into cidade (nome,estado_id) values ('Entre Rios do Oeste', 87);