insert into estado (nome,sigla,pais_id) values ('Asunción', '', 172);
insert into estado (nome,sigla,pais_id) values ('Concepción', '', 172);
insert into estado (nome,sigla,pais_id) values ('San Pedro', '', 172);
insert into estado (nome,sigla,pais_id) values ('Cordillera', '', 172);
insert into estado (nome,sigla,pais_id) values ('Guairá', '', 172);
insert into estado (nome,sigla,pais_id) values ('Caaguazú', '', 172);
insert into estado (nome,sigla,pais_id) values ('Caazapá', '', 172);
insert into estado (nome,sigla,pais_id) values ('Itapúa', '', 172);
insert into estado (nome,sigla,pais_id) values ('Misiones', '', 172);
insert into estado (nome,sigla,pais_id) values ('Paraguarí', '', 172);
insert into estado (nome,sigla,pais_id) values ('Alto Paraná', '', 172);
insert into estado (nome,sigla,pais_id) values ('Central', '', 172);
insert into estado (nome,sigla,pais_id) values ('Ñeembucú', '', 172);
insert into estado (nome,sigla,pais_id) values ('Amambay', '', 172);
insert into estado (nome,sigla,pais_id) values ('Canindeyú', '', 172);
insert into estado (nome,sigla,pais_id) values ('Presidente Hayes', '', 172);
insert into estado (nome,sigla,pais_id) values ('Boquerón', '', 172);
insert into estado (nome,sigla,pais_id) values ('Alto Paraguay', '', 172);