insert into estado (nome,sigla,pais_id) values ('BUENOS AIRES', '', 10);
insert into estado (nome,sigla,pais_id) values ('CATAMARCA', '', 10);
insert into estado (nome,sigla,pais_id) values ('CHACO', '', 10);
insert into estado (nome,sigla,pais_id) values ('CHUBUT', '', 10);
insert into estado (nome,sigla,pais_id) values ('CORDOBA', '', 10);
insert into estado (nome,sigla,pais_id) values ('CORRIENTES', '', 10);
insert into estado (nome,sigla,pais_id) values ('ENTRE RIOS', '', 10);
insert into estado (nome,sigla,pais_id) values ('FORMOSA', '', 10);
insert into estado (nome,sigla,pais_id) values ('JUJUY', '', 10);
insert into estado (nome,sigla,pais_id) values ('LA PAMPA', '', 10);
insert into estado (nome,sigla,pais_id) values ('LA RIOJA', '', 10);
insert into estado (nome,sigla,pais_id) values ('MENDOZA', '', 10);
insert into estado (nome,sigla,pais_id) values ('MISIONES', '', 10);
insert into estado (nome,sigla,pais_id) values ('NEUQUEN', '', 10);
insert into estado (nome,sigla,pais_id) values ('RIO NEGRO', '', 10);
insert into estado (nome,sigla,pais_id) values ('SALTA', '', 10);
insert into estado (nome,sigla,pais_id) values ('SAN JUAN', '', 10);
insert into estado (nome,sigla,pais_id) values ('SAN LUIS', '', 10);
insert into estado (nome,sigla,pais_id) values ('SANTA CRUZ', '', 10);
insert into estado (nome,sigla,pais_id) values ('SANTA FE', '', 10);
insert into estado (nome,sigla,pais_id) values ('SANTIAGO DEL ESTERO', '', 10);
insert into estado (nome,sigla,pais_id) values ('TIERRA DEL FUEGO', '', 10);
insert into estado (nome,sigla,pais_id) values ('TUCUMAN', '', 10);