insert into estado (nome,sigla,pais_id) values ('Acre', 'AC', 30);
insert into estado (nome,sigla,pais_id) values ('Alagoas', 'AL', 30);
insert into estado (nome,sigla,pais_id) values ('Amazonas', 'AM', 30);
insert into estado (nome,sigla,pais_id) values ('Amapá', 'AP', 30);
insert into estado (nome,sigla,pais_id) values ('Bahia', 'BA', 30);
insert into estado (nome,sigla,pais_id) values ('Ceará', 'CE', 30);
insert into estado (nome,sigla,pais_id) values ('Distrito Federal', 'DF', 30);
insert into estado (nome,sigla,pais_id) values ('Espírito Santo', 'ES', 30);
insert into estado (nome,sigla,pais_id) values ('Goiás', 'GO', 30);
insert into estado (nome,sigla,pais_id) values ('Maranhão', 'MA', 30);
insert into estado (nome,sigla,pais_id) values ('Minas Gerais', 'MG', 30);
insert into estado (nome,sigla,pais_id) values ('Mato Grosso do Sul', 'MS', 30);
insert into estado (nome,sigla,pais_id) values ('Mato Grosso', 'MT', 30);
insert into estado (nome,sigla,pais_id) values ('Pará', 'PA', 30);
insert into estado (nome,sigla,pais_id) values ('Paraíba', 'PB', 30);
insert into estado (nome,sigla,pais_id) values ('Pernambuco', 'PE', 30);
insert into estado (nome,sigla,pais_id) values ('Piauí', 'PI', 30);
insert into estado (nome,sigla,pais_id) values ('Paraná', 'PR', 30);
insert into estado (nome,sigla,pais_id) values ('Rio de Janeiro', 'RJ', 30);
insert into estado (nome,sigla,pais_id) values ('Rio Grande do Norte', 'RN', 30);
insert into estado (nome,sigla,pais_id) values ('Rondônia', 'RO', 30);
insert into estado (nome,sigla,pais_id) values ('Roraima', 'RR', 30);
insert into estado (nome,sigla,pais_id) values ('Rio Grande do Sul', 'RS', 30);
insert into estado (nome,sigla,pais_id) values ('Santa Catarina', 'SC', 30);
insert into estado (nome,sigla,pais_id) values ('Sergipe', 'SE', 30);
insert into estado (nome,sigla,pais_id) values ('São Paulo', 'SP', 30);
insert into estado (nome,sigla,pais_id) values ('Tocantins', 'TO', 30);