insert into estado (nome,sigla,pais_id) values ('Alaska', 'AK', 230);
insert into estado (nome,sigla,pais_id) values ('Alabama', 'AL', 230);
insert into estado (nome,sigla,pais_id) values ('Arkansas', 'AR', 230);
insert into estado (nome,sigla,pais_id) values ('Arizona', 'AZ', 230);
insert into estado (nome,sigla,pais_id) values ('California', 'CA', 230);
insert into estado (nome,sigla,pais_id) values ('Colorado', 'CO', 230);
insert into estado (nome,sigla,pais_id) values ('Connecticut', 'CT', 230);
insert into estado (nome,sigla,pais_id) values ('District of Columbia', 'DC', 230);
insert into estado (nome,sigla,pais_id) values ('Delaware', 'DE', 230);
insert into estado (nome,sigla,pais_id) values ('Florida', 'FL', 230);
insert into estado (nome,sigla,pais_id) values ('Georgia', 'GA', 230);
insert into estado (nome,sigla,pais_id) values ('Hawaii', 'HI', 230);
insert into estado (nome,sigla,pais_id) values ('Iowa', 'IA', 230);
insert into estado (nome,sigla,pais_id) values ('Idaho', 'ID', 230);
insert into estado (nome,sigla,pais_id) values ('Illinois', 'IL', 230);
insert into estado (nome,sigla,pais_id) values ('Indiana', 'IN', 230);
insert into estado (nome,sigla,pais_id) values ('Kansas', 'KS', 230);
insert into estado (nome,sigla,pais_id) values ('Kentucky', 'KY', 230);
insert into estado (nome,sigla,pais_id) values ('Louisiana', 'LA', 230);
insert into estado (nome,sigla,pais_id) values ('Massachusetts', 'MA', 230);
insert into estado (nome,sigla,pais_id) values ('Maryland', 'MD', 230);
insert into estado (nome,sigla,pais_id) values ('Maine', 'ME', 230);
insert into estado (nome,sigla,pais_id) values ('Michigan', 'MI', 230);
insert into estado (nome,sigla,pais_id) values ('Minnesota', 'MN', 230);
insert into estado (nome,sigla,pais_id) values ('Missouri', 'MO', 230);
insert into estado (nome,sigla,pais_id) values ('Mississippi', 'MS', 230);
insert into estado (nome,sigla,pais_id) values ('Montana', 'MT', 230);
insert into estado (nome,sigla,pais_id) values ('North Carolina', 'NC', 230);
insert into estado (nome,sigla,pais_id) values ('North Dakota', 'ND', 230);
insert into estado (nome,sigla,pais_id) values ('Nebraska', 'NE', 230);
insert into estado (nome,sigla,pais_id) values ('New Hampshire', 'NH', 230);
insert into estado (nome,sigla,pais_id) values ('New Jersey', 'NJ', 230);
insert into estado (nome,sigla,pais_id) values ('New Mexico', 'NM', 230);
insert into estado (nome,sigla,pais_id) values ('Nevada', 'NV', 230);
insert into estado (nome,sigla,pais_id) values ('New York', 'NY', 230);
insert into estado (nome,sigla,pais_id) values ('Ohio', 'OH', 230);
insert into estado (nome,sigla,pais_id) values ('Oklahoma', 'OK', 230);
insert into estado (nome,sigla,pais_id) values ('Oregon', 'OR', 230);
insert into estado (nome,sigla,pais_id) values ('Pennsylvania', 'PA', 230);
insert into estado (nome,sigla,pais_id) values ('Rhode Island', 'RI', 230);
insert into estado (nome,sigla,pais_id) values ('South Carolina', 'SC', 230);
insert into estado (nome,sigla,pais_id) values ('South Dakota', 'SD', 230);
insert into estado (nome,sigla,pais_id) values ('Tennessee', 'TN', 230);
insert into estado (nome,sigla,pais_id) values ('Texas', 'TX', 230);
insert into estado (nome,sigla,pais_id) values ('Utah', 'UT', 230);
insert into estado (nome,sigla,pais_id) values ('Virginia', 'VA', 230);
insert into estado (nome,sigla,pais_id) values ('Vermont', 'VT', 230);
insert into estado (nome,sigla,pais_id) values ('Washington', 'WA', 230);
insert into estado (nome,sigla,pais_id) values ('Wisconsin', 'WI', 230);
insert into estado (nome,sigla,pais_id) values ('West Virginia', 'WV', 230);
insert into estado (nome,sigla,pais_id) values ('Wyoming', 'WY', 230);